spring.application.name=demo

# ===========================
# Server Configuration
# ===========================
server.port=8080

# ===========================
# Active Profile (use 'dev' for H2, 'prod' for MySQL)
# ===========================
spring.profiles.active=dev

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true


# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# Admin seed
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}

 
# App
app.name=${APP_NAME}
app.admin-email=${APP_ADMIN_EMAIL}
 
# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173,https://yourdomain.com
# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION} 

spring.config.import=optional:file:.env[.properties]